### ISSUE TITLE
Temperature feature

### ISSUE THREAD

**Issue by Merewether** [myriadrf/LimeSDR-Mini-v2_GW#2]
There is a nearly insignificant bug in CMD_ANALOG_VAL_RD. When reading the temperature from the LM75, on line 975 the code is:
		spirez = i2c_rdata[0];
I think it should be:
		spirez = i2c_rdata[1];

**Comment by Merewether** [comment]
Actually, I think the code should look like this:
converted_val = (signed short int)i2c_rdata[0];
converted_val = converted_val << 8;
converted_val = converted_val | i2c_rdata[1];
converted_val = 5 * (converted_val >> 7);

**Comment by vbuitvydas** [comment]
> Actually, I think the code should look like this: converted_val = (signed short int)i2c_rdata[0]; converted_val = converted_val << 8; converted_val = converted_val | i2c_rdata[1]; converted_val = 5 * (converted_val >> 7);

Fixed [typo in main.c](https://github.com/myriadrf/LimeSDR-Mini-v2_GW/commit/24760b88e1ce14ca0be098e16f91e01eb6d97fe9#diff-cdbb19510a9ba7e84a8bf3dad12edc2c48d127af10f3e9073edc883173933974L975). This only affects 0.5 precision reading. Keeping same code to have it consistent with other projects.

Thanks @Merewether.
